# Generated by Django 4.2.7 on 2023-11-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='total_revenue',
            new_name='total_profit',
        ),
        migrations.AddField(
            model_name='consultation',
            name='revenue',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
